//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW_SOAP_DotNet.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://app/", ConfigurationName="ServiceReference1.OlaService")]
    public interface OlaService {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://app/OlaService/cumprimentarRequest", ReplyAction="http://app/OlaService/cumprimentarResponse")]
        HW_SOAP_DotNet.ServiceReference1.cumprimentarResponse cumprimentar(HW_SOAP_DotNet.ServiceReference1.cumprimentarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app/OlaService/cumprimentarRequest", ReplyAction="http://app/OlaService/cumprimentarResponse")]
        System.Threading.Tasks.Task<HW_SOAP_DotNet.ServiceReference1.cumprimentarResponse> cumprimentarAsync(HW_SOAP_DotNet.ServiceReference1.cumprimentarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cumprimentarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cumprimentar", Namespace="http://app/", Order=0)]
        public HW_SOAP_DotNet.ServiceReference1.cumprimentarRequestBody Body;
        
        public cumprimentarRequest() {
        }
        
        public cumprimentarRequest(HW_SOAP_DotNet.ServiceReference1.cumprimentarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class cumprimentarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public cumprimentarRequestBody() {
        }
        
        public cumprimentarRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cumprimentarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cumprimentarResponse", Namespace="http://app/", Order=0)]
        public HW_SOAP_DotNet.ServiceReference1.cumprimentarResponseBody Body;
        
        public cumprimentarResponse() {
        }
        
        public cumprimentarResponse(HW_SOAP_DotNet.ServiceReference1.cumprimentarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class cumprimentarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public cumprimentarResponseBody() {
        }
        
        public cumprimentarResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OlaServiceChannel : HW_SOAP_DotNet.ServiceReference1.OlaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OlaServiceClient : System.ServiceModel.ClientBase<HW_SOAP_DotNet.ServiceReference1.OlaService>, HW_SOAP_DotNet.ServiceReference1.OlaService {
        
        public OlaServiceClient() {
        }
        
        public OlaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OlaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OlaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OlaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HW_SOAP_DotNet.ServiceReference1.cumprimentarResponse HW_SOAP_DotNet.ServiceReference1.OlaService.cumprimentar(HW_SOAP_DotNet.ServiceReference1.cumprimentarRequest request) {
            return base.Channel.cumprimentar(request);
        }
        
        public string cumprimentar(string arg0) {
            HW_SOAP_DotNet.ServiceReference1.cumprimentarRequest inValue = new HW_SOAP_DotNet.ServiceReference1.cumprimentarRequest();
            inValue.Body = new HW_SOAP_DotNet.ServiceReference1.cumprimentarRequestBody();
            inValue.Body.arg0 = arg0;
            HW_SOAP_DotNet.ServiceReference1.cumprimentarResponse retVal = ((HW_SOAP_DotNet.ServiceReference1.OlaService)(this)).cumprimentar(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HW_SOAP_DotNet.ServiceReference1.cumprimentarResponse> HW_SOAP_DotNet.ServiceReference1.OlaService.cumprimentarAsync(HW_SOAP_DotNet.ServiceReference1.cumprimentarRequest request) {
            return base.Channel.cumprimentarAsync(request);
        }
        
        public System.Threading.Tasks.Task<HW_SOAP_DotNet.ServiceReference1.cumprimentarResponse> cumprimentarAsync(string arg0) {
            HW_SOAP_DotNet.ServiceReference1.cumprimentarRequest inValue = new HW_SOAP_DotNet.ServiceReference1.cumprimentarRequest();
            inValue.Body = new HW_SOAP_DotNet.ServiceReference1.cumprimentarRequestBody();
            inValue.Body.arg0 = arg0;
            return ((HW_SOAP_DotNet.ServiceReference1.OlaService)(this)).cumprimentarAsync(inValue);
        }
    }
}
